logger:
  level: debug
server:
  port: :9090
db:
  host: localhost
  port: 27017
  user: root
  pass: example
  name: dvault
postgres:
  host: localhost
  port: 5432
  user: postgres
  pass: postgres
  name: dvault
  auto_migrate: true
