version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example